classdef Convolution2DHostStrategy < nnet.internal.cnn.layer.util.ExecutionStrategy
    % Convolution2DHostStrategy   Execution strategy for running the convolution on the host
    
    %   Copyright 2016 The MathWorks, Inc.
    
    methods
        function [Z, memory] = forward(~, X, ...
                weights, bias, ...
                verticalPad, horizontalPad, ...
                verticalStride, horizontalStride)
            Z = nnet.internal.cnnhost.convolveForward2D( ...
                X, weights, ...
                verticalPad, horizontalPad, ...
                verticalStride, horizontalStride);
            Z = Z + bias;
            memory = [];
        end
        
        function dX = backward( ~, ...
                X, weights, dZ, ...
                 padHeight, padWidth, ...
                strideHeight, strideWidth)
            dX = nnet.internal.cnnhost.convolveBackwardData2D( ...
                X, weights, dZ, ...
                padHeight, padWidth, ...
                strideHeight, strideWidth);
        end
        
        function gradients = gradients(~, ...
                X, weights, dZ, ...
                 padHeight, padWidth, ...
                strideHeight, strideWidth)
            gradients{1} = nnet.internal.cnnhost.convolveBackwardFilter2D( ...
                X, weights, dZ, ...
                padHeight, padWidth, ...
                strideHeight, strideWidth);
            gradients{2} = nnet.internal.cnnhost.convolveBackwardBias2D(dZ);
        end
        
    end
end